### ISSUE TITLE
Pass arbitrary schema options

### ISSUE THREAD

**Issue by mike-burns** [thoughtbot/json-matchers#10]
We do want `strict: true`, but we also need to pass a fragment specifier.

Our JSON schemae looks like this:

```json
{
  "v1.purchases.index.response": {
    "properties": { "number_of_purchases: { "type": "integer", "required": true } } },
  "v1.users.index.response": {
    "properties": { "amount_of_awesomeness: { "type": "integer", "required": true } } }
}
```

So we must specify:

```ruby
JSON::Validator.fully_validate(schema, json, fragment: "#/v1.purchases.index.response", strict: true)
```

Therefore, we would like to be able to specify additional arbitrary schema options. But really we just need the `fragment` option.

**Comment by seanpdoyle** [comment]
@mike-burns I think this makes sense as a feature.

Right now, the matcher:

```rb
expect(response).to match_response_schema("the-name-that-is-also-a-path-probably")
```

does a lookup based on the name/path passed into the matcher.

That code lives [here](https://github.com/thoughtbot/json-matchers/blob/b5e274540bcac1e52bd008b9a0f4f690c26b9025/lib/json/matchers/rspec.rb#L58).

We could probably make that accept your large JSON schema hash, along with an XPath style fragment, right?

**Comment by mike-burns** [comment]
I'm picturing something like:

```ruby
expect(response).to match_response_schema(
  "the-name-that-is-also-a-path-probably",
  fragment: "#/v1.purchases.index.response",
)
```

Where that hash is optional.

And then in https://github.com/thoughtbot/json-matchers/blob/b5e274540bcac1e52bd008b9a0f4f690c26b9025/lib/json/matchers/rspec.rb#L59 it would pass an options hash (e.g. `{ strict: true }.merge(user_options)`), and in https://github.com/thoughtbot/json-matchers/blob/b5e274540bcac1e52bd008b9a0f4f690c26b9025/lib/json/matchers/matcher.rb#L9 it would pass the schema options there.

(It's called a JSON pointer fragment.)

**Comment by seanpdoyle** [comment]
This was resolved by https://github.com/thoughtbot/json-matchers/pull/11
